[package]
name = "view_nannou"
version = "0.1.0"
edition = "2018"

[dependencies]

broker = { path = "../broker" }

crossbeam = "0.8.1"
nannou = "0.17.1"

serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
